# Generated by Django 5.1.7 on 2025-03-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
