# Generated by Django 5.1.7 on 2025-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0002_alter_stream_description_alter_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgrade',
            name='stream',
        ),
        migrations.AddField(
            model_name='classgrade',
            name='stream',
            field=models.ManyToManyField(to='shule_app.stream'),
        ),
    ]
