# Generated by Django 5.1.7 on 2025-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0003_remove_classgrade_stream_classgrade_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgrade',
            name='stream',
            field=models.ManyToManyField(related_name='classgrades', to='shule_app.stream'),
        ),
    ]
