# Generated by Django 5.1.7 on 2025-03-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0004_alter_classgrade_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='ac_year',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='term',
            field=models.ManyToManyField(related_name='academicyears', to='shule_app.term'),
        ),
    ]
