# Generated by Django 5.1.7 on 2025-03-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0005_remove_term_ac_year_academicyear_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgrade',
            name='ac_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shule_app.academicyear', verbose_name='Academic Year'),
        ),
    ]
