# Generated by Django 5.1.7 on 2025-03-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0008_alter_assignment_due_date'),
        ('shule_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_grade',
        ),
        migrations.AddField(
            model_name='student',
            name='class_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shule_app.classgrade'),
        ),
    ]
