# Generated by Django 5.1.7 on 2025-03-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_app', '0008_alter_assignment_due_date'),
        ('shule_users', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shule_app.classgrade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone_number', models.IntegerField(null=True)),
                ('other_phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50)),
                ('relation', models.CharField(max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule_users.student')),
            ],
        ),
    ]
