# Generated by Django 5.1.7 on 2025-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_users', '0004_teacher_class_grade_teacher_is_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentguardian',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
