# Generated by Django 5.1.7 on 2025-03-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule_users', '0005_alter_parentguardian_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentguardian',
            name='name',
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='f_name',
            field=models.CharField(default='test', max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='l_name',
            field=models.CharField(default='test', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='m_name',
            field=models.CharField(default='test', max_length=100, verbose_name='Middle Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='parent_id',
            field=models.CharField(default=1001, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=20),
        ),
    ]
