# Generated by Django 5.1.7 on 2025-03-18 20:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shule_users', '0006_remove_parentguardian_name_parentguardian_f_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentGuardian',
            new_name='ParentOrGuardian',
        ),
    ]
